from pawpal_system import Owner, Pet, Task, Scheduler

# generated by copilot + my edits
def test_owner_can_manage_pets_and_scheduler_can_create_schedule():
    owner = Owner(owner_id=1, owner_name="Shu", email="email@example.com")
    cat1 = Pet(name="Sanu", age=3)
    cat2 = Pet("Momo", 4)

    owner.add_pet(cat1)
    owner.add_pet(cat2)

    assert owner.pets == [cat1, cat2]

    task1 = Task(description="Feed cat", due_time="09:00", frequency=1)
    cat1.add_task(task1)

    task2 = Task(description="Feed cat", due_time="09:30", frequency=1)
    cat2.add_task(task2)

    task3 = Task(description="Walk cat", due_time="17:00", frequency=1)
    cat1.add_task(task3)

    task4 = Task(description="Walk cat", due_time="16:30", frequency=1)
    cat2.add_task(task4)

    scheduler = Scheduler(start_time="08:00", end_time="20:00", duration=12, owner=owner)
    schedule = scheduler.create_schedule()

    print("Today's schedule:")
    for task in schedule:
        print(f"- {task.description} ({task.due_time})")


test_owner_can_manage_pets_and_scheduler_can_create_schedule()