from pawpal_system import Owner, Pet, Task, Scheduler
import datetime

# generated by copilot + my edits
def test_owner_can_manage_pets_and_scheduler_can_create_schedule():
    owner = Owner(owner_id=1, owner_name="Shu", email="email@example.com")
    cat1 = Pet(name="Sanu", age=3)
    cat2 = Pet("Momo", 4)

    owner.add_pet(cat1)
    owner.add_pet(cat2)

    assert owner.pets == [cat1, cat2]

    task1 = Task(description="Feed Sanu", due_time=datetime.time(9, 0), due_date= "Friday", frequency= "daily", pet_name = "Sanu")
    cat1.add_task(task1)

    task3 = Task(description="Walk Sanu", due_time=datetime.time(17, 0), due_date= "Friday", frequency= "weekly", pet_name = "Sanu")
    cat1.add_task(task3)

    task2 = Task(description="Feed Momo", due_time=datetime.time(9, 30), due_date= "Friday", frequency= "daily", pet_name = "Momo")
    cat2.add_task(task2)

    task4 = Task(description="Walk Momo", due_time=datetime.time(16, 30), due_date= "Friday", frequency= "weekly", pet_name = "Momo")
    cat2.add_task(task4)

    scheduler = Scheduler(start_time="08:00", end_time="20:00", duration=12, owner=owner)
    schedule = scheduler.create_schedule()
    time_sort_schedule = scheduler.sort_by_time() #sorts the schedule by time
    cat1_schedule = scheduler.filter_by_pet("Sanu") # sorts the schedule by the pet
    cat2_schedule = scheduler.filter_by_pet("Momo")

    print("Today's schedule:")  #output of schedule
    for task in schedule:
        print(f"- {task.description} ({task.due_time})")

    print("Schedule sorted by time:")   # output of schedule when sorted by time
    for task in time_sort_schedule:
        print(f"- {task.description} ({task.due_time})")

    print("Schedule filtered by cat1 - Sanu:")    #output of schedule when filtered by cat1
    for task in cat1_schedule:
        print(f"- {task.description} ({task.due_time})")

    print("Schedule filtered by cat2 - Momo:")    #output of schedule when filtered by cat2
    for task in cat2_schedule:
        print(f"- {task.description} ({task.due_time})")



test_owner_can_manage_pets_and_scheduler_can_create_schedule()